---
title: "構造的因果モデルの基礎 輪読 ＃1"
subtitle: "第1章 はじめに"
author: "谷口友哉"
date: "`r format(Sys.time(),'%Y/%m/%d')`"
output:
  revealjs::revealjs_presentation:
    reveal_option:
      slideNumber: 'c/t'
      center: false
    #pandoc_args: [
    #  '--from', 'markdown+autolink_bare_uris+tex_math_single_backslash-implicit_figures'
    #]
    self_contained: true
    theme: sky
    css: "for-revealjs.css"
---

# 1.1 背景

## 現実社会において

* 興味ある現象の因果関係を明らかにし、それに従い行動を選択する場面にしばしば遭遇
* この時実質科学の諸分野のニーズに応え得る記述表現で十分
* 例えば、興味ある行動をとったときの実際に取ったときにどのような結果が生じるか(因果効果 : causal effect)を知りたいなら,そのことが定量的かつ合理的に評価できるもので十分
* ゆえに、時には過剰なほど慎重な態度で因果関係の解析に臨み、大胆な態度で因果関係を簡略化して記述しようとする

## 実際問題

* 興味ある現象に関係する事柄は数多く存在し,複雑に絡み合っている.
* よって,原因を突き止めたり,因果関係を明らかにしたり,興味ある行動をとったときに何が起こるのかを予測することは簡単ではない.
* それゆえ因果関係に関わる多くの問題を解決することは,実質科学における主要な研究目的の一つ.

## ランダム化実験(randomized experiment)

* 因果関係に関わる多くの問題を解決するための主力な方法論
* コスト面、技術面、倫理面などの理由から困難なケースも多い
* 人為的な操作が加えられていない現象を観察し、そこから因果関係を推論
* このような活動を**介入 (外的操作) **を伴わない**観察研究に基づく因果推論 (causal inference)**、あるいは単に観察研究に基づく因果推論という

## 因果関係に関わる問題を解決するには

* 興味ある現象を多角的に検討することが不可欠
  * 先人たちの「因果とは何か？」という問い
  * 複数の研究領域を通じて分野横断的に議論されてきた
* データという強力なエビデンスを研究対象とする統計科学は因果関係を取り巻く様々な問題を解決する有力なツールとして広く用いられている

## 統計科学における因果推論

* *The Grammar of  Sience*' (Pearson,1911) 第6章において、
"No phenomena are causal..." と述べて以来、因果関係の概念が排除された状態が続く
* 実験計画法 (Fisher,1935) を除いて、相関関係だけでは立証することのできない因果関係が数理統計学の範疇で議論されることはほぼなかった
  * ランダム割り付けという因果関係に基づいて定義される概念が導入
* その他の数理統計学では、ランダム割り付けなどの特別な因果仮定を必要としない
* 確率論に因果関係を記述するツールが存在しなかった

## 一方、医学・工学・社会科学の分野では

* 観察データと専門知識を融合させた因果推論が数多く行われてきた
* しかし統計手法の誤用も多く見られる
  * 例：品質管理の分野
  * 操業データにおいて要因と特性（反応）の区別がなされている時、回帰分析による因果効果の推定を行い、品質特性を予測、制御、調節
  * このような統計解析では要因間の因果関係が明示的にモデル化や定式化されることは少ない

## 要因間に相関関係が認められる時

* 相関関係が
  (1) 2つの要因間の因果関係によって生じたのか
  (2) 2つの要因の共通原因となる第3の要因が存在し,その要因の変動によって生じたのか
  を検討せず行った解析結果は、大きな誤りを導く可能性があることが指摘

# 1.2 有効グラフを用いた因果推論

## パス解析(path analysis) Wright,1921

* 定性的因果仮説を積極的に解析へ取り入れ、因果効果を定量的に評価するための有力な方法論
* 遺伝学の分野で開発
* 構造方程式モデル(structural equation model;SEM) Wold,1954 として計量経済学の分野で発展
* 特徴
  (1) パスダイアグラム(path diagram)による定性的因果仮説の視覚表現
  (2) パス係数(path coefficient)による変数間の相関の分解
  (3) 直接効果(direct effect)と総合効果(total effect)の区別

* 変数間の因果関係がパスダイアグラムという有向グラフ(directed graph) および線形構造方程式モデル(linear SEM) によって正しく記述されているとき,相関情報に基づいて直接効果や総合効果を定量的に推論する方法論

## パス解析における総合効果と直接効果

* XからYへの総合効果
<div class="box">
共変量(covariate)を全て一定の値に固定したうえで、外的操作(intervention manipulation)により、Xの値を一単位変化させた時のYの期待値の変化量
</div>
* XからYへの直接効果
<div class="box">
Yの影響を受けない変数のうちXを除いたものを外的操作によって全て一定の値に固定したうえで、外的操作によりXの値を一単位変化させた時のYの期待値の変化量
</div>
* 共変量：XやYの影響を受けない変数
* 外的操作によりXの値を一単位変化させる：共変量がとる値とは無関係にXの値を一単位変化させること(詳しくは第5.3節)
* (筆者の知る限り)直接効果や総合効果にこのような解釈を明示的に与えたのはPearl(1998)

## グラフィカルモデルの出現

##  有向グラフを用いた因果推論のフレームワークにおける仮定(Pearl,2009a)

* (1) 因果関係は,有効グラフ上に記述される変数,有効グラフ上には現れないもののグラフ上にある変数の挙動を規定する錯乱項 (random disturbance),そしてデータ生成過程 (data generating process) を表現した構造方程式モデルに基づいて記述される
* (2) 構造方程式モデルに含まれる構造方程式のいくつかが構造的に変化したとしても,それらの変化がその他の構造方程式の構造に影響を与えることはない.この条件を満たす構造方程式モデルは自律的 (autonomous) であると呼ばれる.
* 自律的構造方程式モデルこそ,Pearlが提案した構造的因果モデル(structural causal model;SCM)

## 統計科学と有効グラフにおける誤差項

## パス解析と構造的因果モデル

## 生成(generation)とは

## データ生成の例

# 1.3 Neyman-Rubinの因果モデル

## 潜在反応モデル(potential outcome model) 

* Neymanによる潜在反応モデル
  * パス解析と同時期に提案
  * 各個体はそれぞれ割り当てられるであろう処理に対応する  
  潜在的な反応を持つ
  * 割り当てられた処理に応じて個体の反応が観測
  * ランダム化実験に限定した議論(Rubin 2005)
* Rubinによる潜在反応モデル
  * 欠測メカニズムと結びつけ、フレームワークを実験研究から  
  観察研究へと拡張

## 潜在反応モデルに基づく因果推論の特徴

<div class="box">
各個体のそれぞれにおいて、ある処理を受けた時の  
反応とその処理を受けなかった時の反応の両方が  
観察できるのであれば、それらを比較することで  
個体レベルでの因果効果が定量的に評価できる
</div>

* 実際には片方の反応しか観測されない
* 何の因果仮定を置かないまま、データから個体レベルの因果効果を定量的に比較できない:**因果推論の基本問題** (Holland 1986)
* 原則個体レベルの因果効果を評価せず、集団レベルの  
因果効果（population level causal effect）を評価

## SUTVA(Stable Unit Treatment Value Assumption)

* 集団レベルの因果効果の定量的評価は**SUTVA**という  
仮定（Runbin,1980,1986）に基づいて議論

<div class="box">
(1) No Interference between Units
* 興味ある処理を受けた時に観測される個体の反応は、他の個体がどのような処理を受けようともその影響を受けない
(2) No Multiple Versions of Treatment
* 処理水準(level) (処理変数がとる値や条件)は  
それぞれ一意に定義される
</div>

* (1)の解析対象
  * 個体が独立で同一分布からサンプリング、あるいはそれに  
  相当するデータ（例：ランダムサンプリング）

## 適切にランダムサンプリングされている時

* ある個体が選ばれたかは他の個体が選ばれたかと無関係
* 他の個体が受ける処理や潜在的な反応とも無関係
* このような状況では、No Interference between Unitsの仮定が成り立つと考える
* 適切にランダムサンプリングされていない場合、  
No Interference between Unitsの仮定の妥当性を  
高めることは難しい
  * 外生性という仮定の妥当性を高める方法は  
  ランダム化実験以外では難しいこととほぼ同じ(詳細は第6.5節)

## 実際の運用上の問題

* ランダムサンプリングが行われていても、即座に  
No Interference between Unitsが成り立つと  
判断できるわけではない
  * 偶発性により、偏ったデータが採取
  * 個体どうしの接触回数の多い環境のなかでのサンプリング
  * 集団の代表性を保証するのが困難であるケース
* できる限り偏りが排除された様々な集団に基づき、  
解析結果の一様性や非一様性を確認しながら  
一般化可能性(詳細は第3.4節)を検討
* **単一の研究に基づく解析結果に囚われると、**  
**因果関係に関する判断を見誤る可能性がある**

## 例：ワクチンの効果を調べる観察研究

* ワクチンを接種すると個体Aが感染症にかかりにくく  
なるかは、個体Aとの接触が多い個体Bがすでに  
ワクチンを接種しているかに依存
* 個体Bがすでにワクチンを接種している
  * 個体Bが感染症にかかりにくくなるため、  
  個体Aが感染症にかかる可能性も小さくなる
* 個体Bがワクチンを接種していない
  * 個体Aは感染症にかかりやすくなる
* 感染症への曝露状況が異なると一般にワクチンの効果の大きさも異なる
  * 個体Aに対するワクチン接種の反応が個体Bがワクチンを  
  接種したかに依存する可能性を示唆
  * 個体間の接触が頻繁に起こるような特定地域で  
  ランダムサンプリングを行っても、  
  No Interference between Unitsの仮定を正当化することは困難

## No Multiple Versions of Treatment

<div class="box">
* 処理水準のそれぞれに対して、割り当てられた  
処理水準内においては異質性が存在しないことを示唆
</div>
* 例えば
  * データ解析の際、連続変数である処理を離散化
  * 複数のカテゴリの離散変数である処理を１つに要約
* 同一カテゴリに含まれる値は区別されないため、  
No Multiple Versions of Treatmentの仮定が  
正当化されない可能性
  
## 例：治療の有無による疾患への影響を調査

* 一言に「治療」と言っても
  * 薬物治療、外科治療
  * 薬物治療にも使われる薬剤は様々
  * 同じ薬剤でも用量が異なる
* 様々な治療があり、治療の質は異なる
* 「治療」に No Multiple Versions of Treatmentを  
仮定すると、全て「治療」という一言で定義され、  
治療の質による違いが考慮されない

## 一致性(consistency)

<div class="box">
個体が興味ある処理を受けたときに生じるであろう  
反応が、実際に処理を受けたときに観測されることを  
数学的に表現したもの  
個体について観測される反応と潜在的な反応を  
結びつける重要な鍵
</div>

* SUTVAに基づいて定義される概念

## SCMと比較した潜在反応モデル

* 潜在反応モデルは
  * 処理の割付メカニズムにアイデアの源泉
  * 欠測値データの解析法を数理基盤
  * 有向グラフを用いた因果推論と比較して、  
  実務家には扱いやすい
* 一方SUTVAと一致性の仮定を通して、
  * 観測される反応に基づいて潜在的な反応が定義
  * 潜在的な反応自身に独立な定義はない
* 筆者の知る限り、以下の問題への明確な答えは  
与えられていない(Pearl,2010a)
  * そもそも潜在的な反応はどのように生成されたか
  * 一致性が成立しないときの潜在的な反応とは何か

## 潜在反応モデルと比較したSCM

* 一方SCMのフレームワークの場合、潜在的な反応は  
データ生成過程と結びつけて定式化
    * No Multiple Versions of Treatmentや一致性について仮定する必要なし
    * むしろデータ生成過程が持つ性質として導かれる

## 因果効果の定量的評価問題

* SCMと潜在反応モデルの立場は異なる
  * どちらの立場でも、因果効果を定量的に評価するために適切な共変量を選択されることが重要視
* 潜在反応モデルでは、
  * 要因間の因果関係をモデル化することを極力避ける工夫
  * 共変量選択問題が詳細に議論されることは少ない
    * シミュレーション評価や感度分析、傾向スコアなどで議論される共変量選択基準の多くは経験的や統計的
    * 因果効果を評価するために十分な共変量の選択を客観的に判断しにくい
* 一方SCMでは、
  * 必要に応じて要因間の因果関係もモデル化される
  * データ生成過程の観点に基づき、客観的な共変量選択基準を  
  与えることが可能
  * データ生成過程の考え方は計算アルゴリズムと相性が良い
    * SCMは情報科学や工学の分野の研究者が因果関係を考える上で  
    有効なツール(たとえば、清水,2017)

# 1.4 相関関係か？因果関係か？

## 1.4.1 チョコレートとノーベル賞

* 国民1人当たりチョコ年間消費量と、国民100万人当たり  
ノーベル賞受賞者数に関する解析事例(Messerli,2012)
* フラバノールを豊富に含むチョコの消費量を取り上げ、「国レベルのチョコ消費量」と国民の認知機能の間に  
どのような関係があるのか？
  * フラバノール:チョコ、ココア、赤ワインなどに含まれ、  
  認知機能の低下を遅らせる、あるいは改善できることが報告
* 「国民100万人当たりのノーベル賞受賞者数」を  
「国民に占める優れた認知機能を持つ人々の割合」に  
対する代表変数とみなし、チョコ消費量とノーベル賞  
受賞者数の相関関係は**0.791**(サンプルサイズ：23か国)
  * スウェーデンを除くと**0.862**

## Messerli（2012）のStudy limitations

<div class="box">
The present data are based on country averages, and the specific chocolate intake of individual Nobel laureates of the past and present remains unknown.
The cumulative dose of chocolate that is needed to sufficiently increase the odds of being asked to travel to Stockholm is uncertain.  
</div>

<div class="box">
Dr.Messerli reports regular daily chocolate consumption, mostly but not exclusively in the form of Lindt's dark varieties.
</div>

* Messerli（2012）はユーモアを交えながら、  
安直なデータ解析への警告

## 筆者が考えるMesserli（2012）の警告

* 因果推論に関して筆者は次の２点の警告がされていると考えた

<div class="box">
1. 2つの項目どうしに強い相関があると言っても、  
それが原因と結果の関係があることを結論づけない
2. 高度情報化社会となった現在、IT技術を駆使すれば、興味ある項目と高い相関関係を有する項目を容易に  
発見できる
</div>

## Messerli（2012）で検討すべきデータ生成過程

(1) チョコ消費量がノーベル賞受賞者数に影響を与える
(2) ノーベル賞受賞者数がチョコ消費量に影響を与える
(3) チョコ消費量とノーベル賞受賞者数の間に共通の原因が存在

* これらの可能性を検討するためにランダム化実験を  
すべきと主張

## 相関と因果

* これまで関係がわからなかった項目間に弱い相関が  
あるとわかったとき
  * その関係は偶然的に生成されたと判断
  * 「なぜ相関関係が弱いのか?」と因果関係を結び付けて判断することは少ない
* 直感的に関係がないと思われていた項目間に強い相関があるとわかったとき
  * 普遍的、つまり因果関係と解釈しようとする
  * 行動を起こしやすい項目が原因、そうでない項目を結果と  
  解釈しようとする人が少なくない
  * 因果関係の正負と言った符号が相関関係と一致していると  
  思い込む人もいる
    
## 介入を伴わない観察研究において

* 起こりうるケース
  * データから導かれた相関関係の有無が因果関係の有無と  
  一致するとは限らない
  * 相関関係はないが因果関係は存在する
  * 相関関係が強くても因果関係は存在しない
* どちらが原因でどちらが結果であるかは問題設定に依存

## Messerli（2012）に触発された研究

* 現在のIT技術を駆使すれば、ノーベル賞受賞者数と  
高い相関を持つ項目を探すことは難しくない
  * Maurage et al（2013）
    * ワイン、お茶、GDP、国民100万人あたりのIKEAの店舗数のそれぞれとノーベル賞受賞者数との相関係数を計算
    * 国の経済力に関する項目がノーベル賞受賞者数と強い相関を持つ
  * Linthwaite and Fuller（2013）
    * ミルク消費量とノーベル賞受賞者数の相関と、チョコ消費量とノーベル賞受賞者数の相関に大きな差異なし
  * Doi et al（2014）
    * 経済力よりも研究活動に関連する項目のほうがノーベル賞受賞者数の  
    予測因子として優れている

## 強い相関がみられたとき

* 強い相関がみられたときに考えられること
  * 必然的か
  * 偶然的か
  * 与えられた状況に固有の知見か
  * 広範囲に適用できる知見か

* 単一の観察研究に基づいてこれらを判断することは困難
* 探索的に発見された知見が、我々にとって有用な情報かどうかは適用場面に依存
  * IKEAの店舗数とノーベル賞受賞者数に強い相関が認められた  
  ことを根拠に、IKEAを誘致するように政府に働きかける？
  
## 1.4.2 おむつとビール　{#beer_diapers}

* 紙おむつを買った人はビールを一緒に買う傾向がある
  * 有名なデータマイニングの成功事例の1つ
  * 米国中西部のある都市では、17時に紙おむつを購入した人は  
  半ダースのビールも合わせて買う傾向
  * おつまみをおむつ棚の近くに配置したら、その時間帯のスナックの売り上げが17%増加
  
* これらの知見は**「米国中西部のある都市」**で  
得られたもの
  * 他の都市や店舗で同じことが言えるかは当時「今後の課題」であり普遍的なものではない

## その後の実地調査（山本,2013）{#yamamoto}

* データが採取された店舗の商圏に工場新設、  
若い家族層が移住
* 夫が仕事帰り（17時以降）におむつとビールを購入
* この現象はこの店舗特有、一般におむつと併売確率が  
高いのはベビー用品
* ポイントカードもない時代にデータがくっきりと  
その店舗の顧客像を浮かび上がらせたという意味で、  
データマイニングの成功事例

## おむつとビールにおける相関と因果 {#beer_diapers_cor}

* 観察研究によって得られた知見（米国中西部のある都市では...ビールもあわせて買う傾向がある）から  
「おむつの棚の近くに...17％増加した」という  
ストーリーを直接的に見出せない
  * 前者はビールとおむつの購買の**相関関係**に基づく記述
  * 「スナックの棚とおむつの棚の距離」について言及していない
  * 後者は「おむつの棚の近くにスナックの棚を配置した」という販売戦略（外的操作）
  * 前者は**相関関係**、後者は**因果関係**
* 相関情報だけで前者から後者を導くことは容易でない

## 相関が分かれば因果は分からなくて良い？

* 何の仮定・知見もなければビッグデータが因果関係を  
語ることはない
* 因果関係が分からなければ目的を達成するための行動を起こせない
  * その行動が有益かどうかも判断できない
* 相関関係と因果関係の取り違えや因果の方向性に対する誤った思い込みが笑い話で済まされない社会問題や  
無駄な行動を誘発するのは稀なことではない（Gilovich,1993）
  * ノーベル賞受賞者数を増やすためにIKEAを誘致？

# 1.5 問題意識

## 因果推論に関する主な課題（Holland,1986）

<div class="box">
1. 観察された因果関係に対する因果構造の解明
2. 観察された因果関係における因果効果の定量的評価
3. 観察された結果に対する原因の究明
</div>

* 興味ある変数XとYについて、XからYへの因果効果を  
定量的に評価することが重要

## 用語の導入

* Y : 反応変数（response variable）or 結果変数（outcome variable）
  * Xの違いによって生じうる個体間の差異で興味の対象となる変数
* X : 処理変数（treatment variable）
  * 個体間の差異を生じさせうる変数のうち興味の対象となる変数
* 現実問題への応用を考えたとき、処理変数を曝露変数（exposure variable）や治療変数と呼ぶほうが  
ふさわしいケースもある
  * 本書では基本的に処理変数で統一

## 外的操作が可能か

* 取り上げる変数が処理変数とみなせるか判断する際に  
検討
* 構造的因果モデルのフレームワークでは問題設定に依存
  * Causation before manipulation (Robins and Richardson,2010)

* ︎処理変数と扱うことができるケース

<div class="box">
  * 仮想的に外的操作可能か  
  * 「もしその項目が〇〇であったなら」といった  
  **反事実的**（counterfactual）問題設定が可能か  
</div>

* 潜在反応モデルのフレームワークでは、  
実際に外的操作が可能かどうかを議論の出発点に
  * No causation without manipulation (Holland,1986)
* 因果関係を議論する上では構造的因果モデルの方が  
自由度が大きい

## 共変量と中間変数

* 共変量（covariate）
  * 処理変数の影響を受けない変数
  * 付随変数（concomitant variable）や背景因子（background factor）とも呼ばれる
  * 交絡因子は共変量の1つに分類
* 中間変数（intermediate variable）
  * 処理変数の影響を受け、かつ反応変数に影響を与える可能性のある変数
* 興味ある変数集合を処理変数、反応変数、共変量、  
中間変数に区別することが因果推論を成功させる  
一つの鍵となる（宮川,2004a）
  * 奥野他（1986）による事例を参考に考える


## 奥野他（1986）の概略 {#about_Okuno}

* 防錆性能と美観性能を付与するために行われる自動車のボディ塗装では塗装膜圧の確保が不可欠
* 塗装膜圧は下塗り・中塗り・上塗りの3層構成
* 中塗りと上塗りは塗料を作業者が吹き付けるため  
塗着率が悪いという問題  
➡︎塗装工程において塗着率が向上、安定する工程条件を設定するために様々な条件で実験（38組のデータ）
  * 塗着率に影響を与える要因は希釈率、吐出量、湿度など  
  10個の項目

## 本書での設定

* 宮川,（2004a）や奥野他（1986）によると
  * 希釈率は操作可能な処理変数
  * 湿度は共変量、吐出量は中間変数であり操作は困難
* 塗着率を反応変数とし、データ生成過程として  
線形構造方程式モデル（詳細は第5章）を仮定

## 適切な工程条件の設定とジレンマ

* 適切な工程条件を設定するには、**処理変数（希釈率）を操作した時の反応変数（塗着率）の分布状態を評価**
* 仮定なしに、「処理変数に対して我々が意図する操作を行っていない状況で得られたデータ」から  
「（実際まだ行っていない）処理変数を操作した時の  
反応変数の分布状態」を評価できるのか？
* 一方で、何かを知りたいならまずはそれを知るための  
行動を起こさなけれなばならない  
➡︎このジレンマを何とかできないか？

## 仮定

* 以下の相関行列が得られた 

||希釈率|吐出量|湿度|塗着率|
|:---:|:---:|:---:|:---:|:---:|
|**希釈率**|1.0000|0.3379|-0.4958|0.2456|
|**吐出量**|0.3379|1.0000|-0.1216|-0.0133|
|**湿度**|-0.4958|-0.1216|1.0000|-0.5402|
|**塗着率**|0.2456|-0.0133|-0.5402|-1.0000|

* 湿度は希釈率と塗着率に対して十分な交絡因子（sufficient confounder）
  * 古典的な逐次的線形回帰分析のフレームワークで  
  データ生成過程が表現できる
* 希釈率と塗着率の相関係数は0.246と正の値  
➡︎希釈率を大きくすれば塗着率も向上する？？

## 塗着率を目的変数とした線形回帰分析1 {#reg1}

* 希釈率、吐出量、湿度を説明変数とする 
<div class="box">
塗着率 = 0.000 × 希釈率 -0.080 × 吐出量 -0.550 × 湿度
</div>


* 希釈率を操作しても工程改善に役立たない？
* 吐出量を操作した方が良い？

## 塗着率を目的変数とした線形回帰分析2 {#reg2}

* 希釈率、湿度を説明変数とする   
<div class="box">
塗着率 = -0.029 × 希釈率 -0.555 × 湿度
</div>

* 希釈率、吐出量を説明変数とする   
<div class="box">
塗着率 = 0.282 × 希釈率 -0.109 × 吐出量
</div>

* それぞれのモデルで希釈率の係数の正負が異なる  
➡︎どの解析結果を信頼し、希釈率にどのような操作を  
行えば良いか？

## 伝統的な線形回帰分析のフレームワーク

* 処理変数、中間変数、共変量が同じ説明変数として  
平等に扱われる
* 機械的な変数選択によって
  * 処理変数が解析から取り除かれる
  * 処理変数の回帰係数の符号が大きく変わる
* 変数選択の目的は予測モデルのシンプルさと  
予測精度の向上
  * 真のデータ生成過程の解明や因果効果の評価を  
  目的としていない


## 有効グラフで記述

* 希釈率と塗着率に関して、湿度がバックドア基準を  
満たすことを確認（詳細は第3.7.2項）
* 希釈率と湿度を説明変数、塗着率を目的変数とした  
回帰分析から  

<div class="box">
希釈率を操作して1単位当たり増加させると  
塗着率の期待値は0.029減少する
</div>
* この結果より
  * 相関係数をみて希釈率を操作し増加させると塗着率は低下
  * 塗着率を向上させるために希釈率を操作することは  
  無意味でない  
* ※因果効果を評価するために用いられる統計モデルが  
予測モデルとして優れているわけではない

## 因果推論が目的とするものの1つ {#one_of_Purpose}

<div class="box">
単なる統計的予測問題を超えて、興味ある因果的尺度を適切に評価するためにどのような変数を観測すれば  
良いのか、観測できない場合にはどのような代替案が  
あるのか、といった**解析方針を与えること**
</div>
