---
title: "How Are Small Businesses Adjusting to COVID-19? Early Evidence from a Survey"
author: "Tomoya Taniguchi"
date: "`r format(Sys.time(),'%Y/%m/%d')`"
output:
  html_document:
    self_contained: TRUE
    df_print: paged
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
editor_options:
  chunk_output_type: inline
---

```{r knitr_init, echo=FALSE, message=FALSE, warning=FALSE}
# library
library(knitr)
#library(rmdformats)
# Global Options
options(max.print = 100, stringsAsFactors = FALSE)
knitr::opts_chunk$set(
  echo = TRUE,
  tidy = TRUE,
  comment = NA,
  warning = FALSE,
  message = FALSE,
  eval = TRUE
)
knitr::opts_knit$set(width = 75)
```


\newcommand{\indep}{\mathop{\,\perp\!\!\!\!\!\perp\,}}
\newcommand{\notindep}{\mathop{\,\perp\!\!\!\!\!/\!\!\!\!\!\perp\,}}
\newcommand{\mat}[1]{\begin{pmatrix} #1 \end{pmatrix}}
\usepackage{color}
\usepackage{amsmath}

## ABSTRACT

[Bartik, A. W.,et al(2020). How are small businesses adjusting to COVID-19? early evidence from a survey (No. w26989). *National Bureau of Economic* Research.](https://bfi.uchicago.edu/wp-content/uploads/BFI_WP_202042.pdf)

* 公衆衛生への影響に加えて、COVID-19は経済にも大きな影響を与えている
* COVID-19が中小企業にどのような影響を与えているのか、また最近の景気刺激策法案の影響を明らかにするために、5,800社以上の中小企業を対象に調査を実施
  * 景気刺激策法案:2020年3月25日、米国上院はCOVID-19パンデミックへの対策として2兆ドルの景気刺激策を可決。同法案は3月27日付けで下院でも可決され、大統領も署名。
* その結果、いくつかの主要なテーマが浮かび上がってきた。
1. 大規模な解雇や閉鎖がすでに発生しているということ。  
    * 調査において、43％の企業が一時的に閉鎖されており、企業は平均して1月と比較して従業員数を40％削減している。
2. これまでの文献と一致して、多くの中小企業が財務的に脆弱であることがわかる。  
    * 例えば、中央値の企業は、毎月の支出が1万ドル以上で、手元にある現金が1ヶ月で1万ドル未満である。
3. 企業はCOVIDに関連した混乱の可能性が高い期間について、大きく異なる信念を持っている。
4. 大多数の企業はCARES法を通じた資金調達を計画していた。
しかし、多くの企業は、官僚的な煩わしさや適格性(資格を有していること？)の確立の難しさなど、援助を利用する上での問題を予想していた。  
    * 「Coronavirus Aid, Relief, and Economic Security （CARES） Act」:米国で2020年3月27日に成立した金融刺激策。新型コロナウイルス感染症に焦点を合わせた3番目の救済法。

## 1. Introduction

* アメリカの中小企業は COVID-19 に起因する経済的混乱をどのように乗り切っているのか、そして CARES 法は彼らの意思決定と将来の見通しにどのように影響を与えるのだろうか？
  * Alignable business networkのメンバーである5,800社以上の中小企業を対象に調査を実施

* 調査で評価し焦点を当てていること
1. 小規模企業の財務の脆弱性の現在のレベル
2. 小規模企業が既に一時的に閉鎖したり、一時的に従業員を解雇している程度
3. この危機がどのくらい続くかについての期待と、それが企業の意思決定にどのように影響しているか
4. CARES法による資金調達を求めるかどうかの意思決定と、それが解雇や閉鎖の意思決定にどのように影響するか

*  我々の結果は、パンデミックがすでに中小企業の間で大規模な混乱を引き起こしていることを示唆している。
* 危機の期間についての企業の考えは様々であるが、中央値の企業経営者は、混乱は真夏まで続くと予想している。
* 企業は様々な方法で調整しており、回答者の70％以上が、CARES法の一部である給与保護プログラム（PPP）に似たプログラムについて尋ねた際に、援助を利用すると予想している。

* さらに、彼らはこの資金調達が他のビジネス上の意思決定に影響を与えることを期待している (レイオフの決定や完全にビジネスに留まることを含む)
* 同時に多くの企業は、管理上の複雑さや適格性への懸念から、CARES法による資金調達の申請には消極的だった。

* COVID19 危機に起因する現在進行中の経済的混乱については、ほとんど前例がない
  * 我々の調査では、すでに起きている大規模な混乱と、中小企業がこの嵐を乗り切るために必要な限られた財源を記録

* 我々の結果は、CARES法融資の実施内容が、中小企業の中期的なソルベンシー(支払い能力)を確保する上で重要な役割を果たす可能性が高いことを示唆
* また、CARES 法の影響は、融資者が契約プロセスの簡素化、適格性と返済ルールの透明性、キャッシュへのアクセスの速さをどの程度優先させるかにも左右されると考えられる。

## 2. Survey Design and Details

* 中小企業のエコシステムに焦点を当てたネットワークベースのプラットフォームであるAlignableとの提携により実施された。
  * Alignableは、企業が知識を共有し、相互に交流することを可能にしており、現在北米全土で460万社の中小企業のネットワークを有している。
  * ネットワークの成長の多くは有機的なもので、外部からのマーケティングはほとんど行われていない。
  * Alignableは定期的にユーザーにアンケート（これを「パルス調査」と呼んでいる）を配信。支払いは行われておらず、参加は完全に任意。
  
* 最初の1週間で7,511件の回答を得た。このうち5,819件は米国に拠点を置く企業に遡ることができ、政策を理解する上で適切なサンプルとなっている。
  * 7,511件の回答は、Alignableの全会員のごく一部（0.017％）に過ぎないが、COVID-19の中で毎週実施しているパルス調査に参加しているAlignableの会員の割合は0.017％をはるかに上回っていることを示している。
  * Alignableでは、50,000～70,000人の会員が週1回のペースでこの調査に参加していると推定しており、これらの活発な回答者と比較して10～15％のコンバージョンレートがあることを示唆

* 標本は3つの方法で選択されている。  
(1) Alignableへの参加を選択した企業  
(2) 調査に積極的に参加することを選択したAlignable企業  
(3) Alignable内で活動している企業のうち、調査への回答を選択した企業の集合  

* **そのためアメリカの中小企業の領域に外挿する場合には、慎重にならざるを得ない理由が多くある**


* 調査では、企業の特徴（企業規模や業種を含む）に関する基本的な情報、COVID-19 危機への現在の対応、今後の危機の行方についての考えなど、合計 43項目の質問が行われた。
  * 一部の質問はスキップロジックに基づいて表示されているため、回答数は少なかった
* またこの調査には、連邦政府の政策の違いが危機の進展に伴って、これらの企業の行動や存続にどのような影響を与えうるかを理解するために、回答者間でランダム化した実験モジュールも含まれている。
  * 具体的には、異なる政策の潜在的な影響を明らかにするために、潜在的な政策の記述をサンプル間で実験的に変化させた。
  * このモジュールについては、セクションVでより詳細に議論。
  * さらなる実験モジュールには、異なる危機の期間を想定した下での意思決定を調査するための回答者間無作為化が含まれていた。
  
## 3. Firm Characteristics and Representativeness 

* この調査には3つの基本的な質問が含まれ、観察可能な次元に沿ってサンプルの代表性を評価することができる  
  * 従業員数
  * 典型的な経費（2020年1月31日現在）
  * 給与支払に充てられる経費  


* 米国国勢調査局が公表している公的統計を用いて、2017年の米国企業の国勢調査で得られた企業データと比較
  * 基礎となるデータは、カウンティ・ビジネス・パターンのサンプリング・フレームから抽出されており、個人事業を含む有給従業員を有する事業所を対象としている。
  * 国勢調査のデータは、大企業から中小企業までを網羅しているが、比較のために従業員数 500 人未満の企業のみを対象とする。

* Alignable ネットワークは、ユーザーが顧客のリード(見込み客)を共有することを可能にしているため、消費者と直接対話する小売業やサービス業にサンプルが偏ってしまう可能性がある。

* 小売業は COVID-19 の混乱に対して特に脆弱であるため、危機によって引き起こされた全体的な混乱を過大評価してしまう可能性がある。

* しかし、後述するように、産業ミックスに関するデータは、サンプルがアメリカの中小企業の広い範囲を代表していることを示唆している。

* 当然のことながら、製造業のような大企業に支配されている産業の割合は低い。

* 図1は、我々のサンプルの規模分布と、経済センサスにおける従業員数500人未満の事業者の規模分布を示したものである。
  * 雇用規模が一致
  * 標本の約 64％の企業は従業員数が 5人未満であるのに対し、経済センサスの約 60％の企業は従業員数が 5人未満である。
  * 両サンプルの約18％の企業は、従業員数が5人から9人である。

* この調査は、大規模な雇用者グループの間では国勢調査とのマッチングが悪くなり、大規模な雇用者の経験をより正確に捉えることができると考えらる

* 今回の調査では、国勢調査データとの同一の比較はできないが、月次経費とその経費のうち給与支払に充てられている割合についての設問から、系列企業の給与支払経費を近似的に算出し、大まかな比較を行った。

* 国勢調査では、W2 の従業員を対象とした年間の給与支払費用が提供されている。

* センサスと一致しているかどうかを知るために、我々の標本で推定した月次の給与支払費用と、米国国勢調査の年間費用の12分の1を比較した。
  * 比較を容易にするために、総雇用者数の推計値で割っている
  * 調査ではW2と1099の雇用を区別していないので、この比較は異なる「人員」が含まれている可能性が高い

* 図 2 は、我々のサンプルにおける月次推計給与費用の規模分布と、一人当たりの調整を用いた国勢調査の比較可能な内訳を示したもの。
  * 一致は不完全であり、特に大企業では不完全である。
  * この不一致は、製造業や専門サービス業の割合が低いことを反映している可能性があり、これらの企業は、国勢調査データの 2 桁 NAICSセクターの中で最も高額な給与を支払っている。

* Appendix表１には、国勢調査との産業別マッチングの詳細が示されている。

* 図3は、サンプルの地理的範囲を示している。Alignableサンプルは、特にカリフォルニア州、ニューヨーク州、フロリダ州、テキサス州からのサンプルで、アメリカ西部のハートランドでは特に疎になっている。
  * この分布は、経済センサスにおける中小企業の分布と定性的に類似

* 図4は、最も人口の多い10の州でのサンプルのシェアを示している。
  * 経済センサスにおける各州内の小規模事業所のシェアも含まれている。
  * 例えば、カリフォルニア州は、当社の Alignable 調査サンプルの 14.4％、国勢調査データに含まれる小規模事業所の 12.5％、米国の総人口の 11.52％を占めている。
  * 我々のサンプルは、海岸部を過大に、イリノイ州を過小に表している。
  
* 全体的に見て、この調査で捕捉されたサンプルには限界があり、アメリカの小規模企業の特定の場所の不完全なスナップショットではないかもしれないが、サンプルは小規模企業のエコシステム全体についての重要な洞察を可能にしている。
  * サンプルは大規模で、ほとんどの主要な業界グループ、州、企業規模のカテゴリーからの企業が含まれている
  
## 4. Responses to the COVID-19 Pandemic and Lockdown

ここで、主な結果を3つのカテゴリーに分類  
1. COVID-19が事業活動と雇用に与えた現在の影響  
2. これらの企業の財務の脆弱性についての結果を、手元資金と継続的な経費で把握して報告  
3. 危機の持続期間と彼ら自身の経済的な生き残りについての彼らの期待に目を向ける  

### Temporary Closings and Employment:臨時休業と雇用

* まずはオーナーに、現在の事業が稼働しているかどうかを聞くことから始める
  * オーナーに、「営業中」か「一時休業」か「永久休業」を回答
  * COVID-19が原因で廃業したのか、何か別の理由で廃業したのかを報告
    * Bloom ら（2013）のように，企業の経営の質を評価することは試みていない。今後の調査では、経営の質の高さが、今回の危機の際にどのような点で企業の閉鎖を防いでいるのかを検証することを期待している。また、今回の危機は、Bazerman and Moore (1994)が論じているように、ストレス下での経営意思決定を理解する機会を提供している。

  * サンプル全体では、企業の41.4％がCOVID-19のために一時的に休業したと報告
  * 1.8％の企業が、パンデミックのために恒久的に休業したと報告。
  * 対照的に、他の理由で一時的に休業したと報告したのはわずか1.3％。
  * 55.4％がまだ営業していたと報告

* 事業主に現在と2020年1月31日現在の従業員数（正社員とパートタイマー）をマトリクスに記入してもらう
  * サンプル全体では正社員の数が 32％減少
  * パートタイム従業員の数は、56％減少
  * これらの結果には、一時的に閉鎖した事業も含まれている。
  * 存続している事業だけを見ると、正社員数は17.5％減少,パートタイム従業員の数は36％減少
  * 雇用全体では大幅に減少しており、1月の人員数の6割程度にとどまっている。
  
* 中大西洋部門では雇用の減少が最も激しく、一時的に休業している企業の割合が最も高い。同地域の企業の54％が閉鎖され、雇用は平均47％減少
* 山岳部が最も影響が少ないが、そこでも39％の企業が一時的に休業し、雇用は32％減少

* 表 2 と表 3 は、企業規模と業種別の内訳を示したもの。
  * 1月の従業員数が 20 人未満の小規模企業ほど廃業する可能性が高い
  * 1月の従業員数が6人から19人の企業は、雇用削減が最も大きい
  * 業種別では、対面式小売業とサービス業が激減
  * 大打撃を受けたとはいえ、専門サービス企業、銀行・金融、不動産、建設業にとってはそれほど極端なものではない
  
* 表4は、企業が直面している問題を現状の経営状況別に示したものである。
  * オーナーに、従業員の病気(健康状態)、サプライチェーン、顧客需要などの問題点を 1～100 点満点で評価してもらった
  * 尺度には数値と、一端が「問題ない」、もう一端が「非常に破壊的」と いうテキストラベルが付けられている。
* 我々は、営業している企業、一時的に休業した企業、恒久的に休業した企業を区別し、それぞれの分野で著しい困難を示している各カテゴリーの企業のシェアを示す。
    * 平均して、企業はサプライチェーンの課題に起因する混乱を100点満点中35点と評価（これは「やや破壊的」の中に含まれる）。
  * 従業員の健康への懸念はより顕著であり、重要度では100点満点中57点（これは「やや破壊的」に対応）と評価
  * 需要の減少はさらに破壊的であり、企業はその重要性を100点満点中78点（非常に破壊的）と評価
  * 休業した企業では需要による混乱が悪化していることが指摘されているが、問題領域の基本的な順位は企業のタイプを問わず一貫している。このことは、需要ショックや従業員の健康への懸念から生じる混乱と比較して、サプライチェーンの問題は今のところあまり顕著ではないことを示唆している。

* これらの結果から、膨大な数の企業が一時的に休業し、労働者を解雇していることが示唆される。これらの企業に、今後数ヶ月間の危機を乗り切るだけのリソースがあるのかどうかを問う。

### Financial Fragility:財政的な脆弱性

* 財政的な脆弱性を測定するために、回答者に「事業の支払いのための追加融資や家族や友人からの資金調達を求めずに利用できる現金（貯金や当座預金など）は大体どれくらいありますか」と尋ねた。
* 次にこの金額を1月31日の月々の支出で割り、追加の融資を求めずに事業を維持できる期間を把握
  * 信用枠や外部からの借入についての情報は収集していないが、需要の縮小の深刻さを考えれば、政府の保証がない限り、これらの信用枠を利用できる可能性は低いと思われる。
  
* 図5 は、2020 年 1 月 31 日の月次経費の倍数としての手元資金のヒストグラムである。
  * 約4分の1の企業が、1ヶ月分の支出に満たない現金を保有している。
  * また約2分の1の企業が1～2ヶ月分の経費を賄えるだけの現金を保有している。

* 図6は、2020年1月31日の月次支出で企業をソートし、危機前の支出と比較した手元資金の平均値と中央値を表にしたもの
  * 毎月の支出が10,000ドル未満の企業では、中央値は1ヶ月分の手元資金を持っている
  * 毎月の支出が10,000ドル以上の企業では、危機前の支出レベルに基づいて、中央値の企業は通常15日未満の現金を保有
  * これらの企業は、通常の支出を満たすために手元に現金を持っていないだけ

* 手元の現金のこれらの限られたレベルは、解雇や休業が非常に普及している理由を容易に説明する
* これらの行動がなければ、これらの企業がどのように給与を満たしていたかを理解することは困難である。
* さらに、まだ営業している企業が、少なくともより多くの信用の注入なしに、既存の労働者を解雇せずに生き残るのかを想像することは困難である。

### Predicting the Path of the Crisis : 危機の道筋を予測する

* 最後にCOVID-19の危機がいつまで続くのか、2020年末に再び営業を再開するのかどうかを企業に予測してもらう

* 危機の終息を予測するために、調査回答者に「最も可能性が高い時期」は何かを尋ね、また、回答に対する信頼度を1～10段階で尋ねた

* 図７に危機終了の予定日の分布を示す。
  * 危機は 5月末までには収束すると考えている回答者が約5分の1を占めている
  * 3割の回答者が、5月末から7月初旬の間に危機は終わると考えている
  * 7月に入っても危機は続くと考えていると回答した企業は半数近く
  
* しかし、各企業は回答に特に自信を持っているわけではなかった。
  * 回答者の50％が、自信のレベルを1～10段階で5以下と回答している。
  * 16％の企業が「2以下」と回答している。
  * 世界の不確実性を考えれば、彼らの不確実性は適切であると思われる。

* 図8 は、2020年12月31日に営業するかどうかについての回答のヒストグラム
  * 全体では、90％以上の人が「営業する可能性は少なくともある程度ある」と考えている
  * また、64%以上の人が「非常に可能性が高い」または「非常に可能性が高い」と回答しており、これは後にオープンする確率の指標として使用
  * 企業家は将来の見通しについて過大に楽観視しているという文献が増えてきている（例えば、Bazerman and Moore 1994 を参照）真の生存率がさらに低い可能性を示唆
  

* 手元資金が多い企業ほど将来に自信を持っている。
  * 企業が（通常の月々の支出と比較して）手元にある現金の数が、標本の中央値よりも多いか少ないかに基づいて分割されていることからも明らかである
  * 手元資金が中央値よりも多い企業の49％が、年末に営業を開始することを「極めて好ましい」と考えている。
  * 手元資金が中央値よりも少ない企業の32％は、営業しているだろうと考えていた。
  * これらの事実の一つの解釈は、流動性が今回の危機を乗り切る自信を生み出しているということである。
  * 従業員 20 人以上の企業では、70％が「非常に可能性が高い」または「非常に可能性が高い」と回答しており、これは経費ベースが高いにもかかわらず、外部のリソースへのアクセスが高いことを示しているのではないか。

* 図表9は、危機の期間に対する考え方によって、「非常に可能性が高い」「非常に可能性が高い」と考える企業の割合が変化していることを示している。
  * また危機は短いと考えている企業ほど、生き残れる可能性が高いと考えている。
  * 危機は長期化すると考えている企業は、より悲観的である
  
### 5. Anticipated Responses to CARES Act Programs 



### 6. Industry Differences in Response to Crisis Duration : 危機の期間への対応における業界の違い

* COVID-19 の混乱は、すべての企業に等しく影響を与えるわけではない
  * 中には、必要不可欠と判断されて営業を続けている事業もあれば、強制的に閉鎖されている企業もある。
  * リモートワークへの移行によって従業員間の伝染を減らすことができる企業もあれば、移行のための設備が整っていない企業もある
  
* ビジネスの根本的な性質と経営能力の両方に関連している様々な理由のために、COVID-19は、一部の人には実存的な脅威を与え、他の人には与えない


* 企業間の格差は、パンデミックの長期化に対するレジリエンスを測定したときに最も顕著に現れる

* 調査では、次のような仮説を立てて質問している：
「COVID-19 の混乱の継続期間によって、あなたの回答がどのように変化するかを理解したい。大部分のCOVID-19の混乱がXヶ月間続くと仮定して、2020年12月31日までにあなたのビジネスが稼働し続ける可能性はどの程度でしょうか？あなたの最善の推測を述べてください。」

  * 期間を1ヶ月、4ヶ月、6ヶ月のいずれかにランダム化し、回答者には可能性が極めて低いものから極めて高いものまでの5段階の尺度を提示
  * 前述のように、説明を簡単にするために、この回答は営業を続ける可能性が高いか低いかの2値アウトカムに変換している
  
* 表5では、この質問に対する回答を業種別に示している。
  * 1ヶ月の危機を想定していると回答した場合、年末までに営業を継続するとの期待感は、芸術、娯楽と個人サービス業を除く全ての業種で70％前後で推移している
  * これらの業種(芸術、娯楽と個人サービス業)では、それぞれ65％、57％に低下


* 企業が半年間の危機を予想するように言われた場合には、平均的な期待値は38％に低下し、セクター間(産業間)では有意な不均一性がある
* 危機が 4ヶ月続いた場合、芸術・娯楽部門の企業の予想生存確率は 45％、6ヶ月続いた場合は 35％と急激に低下する。
* 個人サービス業の企業の期待される開業確率は、危機が6ヶ月続いた場合には 22％にまで低下する。

* 外食産業は特に長い危機に弱いようだ
  * レストランの経営者は、危機が 1ヶ月続くと72％の確率で生き残れると考えているが、危機が 4 ヶ月続くと30％の確率でしか生き残れないと考えている。危機が 6ヶ月間続く場合は、15%の確率で生き残れると考えている

* 同様に、観光業や宿泊業の企業の生存確率は6ヶ月後には27％に低下

* 一方、銀行・金融、不動産、個人サービス業は、これらの露出度の高いセクター(産業)よりも、長期的な混乱を乗り切ることができるだろうと述べている  

これらの結果は以下の２点を示唆   

* **危機が何ヶ月も続くと、わが国(アメリカ)の経済と中小企業のネットワークへのダメージがはるかに大きくなることを示唆**  

* **経済の早期再開を安全に導くことができる政策が、大きな経済効果をもたらすことを示唆**


### 7. Conclusion

* 中小企業は米国の労働者の約 50％を雇用している

* しかし、我々の調査結果は、多くの中小企業の財務の脆弱性と、現在の危機の影響をいかに深く受けているかを浮き彫りにしている。

* 小売業に偏った標本では、43％の企業が一時的に休業し、雇用が40％減少していることがわかった。

* これは、1930 年代以降、アメリカの小規模企業にとっては、ほとんど平行して起こったことのない衝撃である。

* 我々の結果は、これらの企業の多くが手元資金をほとんど持っていないことを示唆している。つまり、**劇的に経費を削減するか、追加の負債を負うか、破産を宣言しなければならないということである**
  * 新しい資金調達の即時性が中期的な結果に影響を与える可能性があることを浮き彫りにしている
  
* 小規模事業者の調査回答では、支援を受けられない場合、多くの事業者が破産する可能性が高いことが示唆されている
  * 2020年3月の最終週の時点で、38社の事業者が、2020年末の時点で営業できる可能性は低いか、やや高いとしか考えていなかった。
  * CARESローンプログラムについての情報を得たことで楽観論が高まったとはいえ、CARES法がアメリカの中小企業の大半が生き残ることを可能にするかどうか、あるいはその影響についての信念が楽観的になりすぎているかどうかは不明
  
  * また、この結果は、経済政策や公衆衛生政策の施策が十分に設計され、持続的に実施されることの重要性を浮き彫りにしている

* 私たちの調査では、政策に関連した3つの結果が目立っている

1. 13％以上の回答者が、申請の煩わしさ、連邦政府が融資を許してくれるのではないかという不信感、複雑な資格規則の心配などの理由で、CARES法PPP融資を受けることを期待していないと回答していることである
  * 申請手続きを合理化し、適格基準や融資免除のルールを明確にすることで、融資を受ける権利を高めることができるかもしれない  

2. レストラン、観光業、個人向けサービス業など、特に影響を受けやすい業種の企業は、危機が 4 ヶ月以上続いた場合、事業を継続することが極めて困難になると予測
  * 経済の停止を安全に短縮できる政策 (例えば、短期的な封じ込め政策の強化など）があれば、経済的に大きなメリットがあることを示唆)  

3. CARES PPP 融資を受けると回答した企業の72％を米国の全ての中小企業に外挿し、全ての企業が最大融資額（経費の 2.5 ヶ月分）を利用すると仮定すると、融資総額は約 4,100 億ドルとなり、現在の CARES 法で割り当てられている 3,490億ドルを幾分上回ることになるだろう。



